version: "3.9"

services:
  auth_api:
    build:
      args:
        uid: ${HOST_UID}
        gid: ${HOST_GID}
      target: production
    command: ["uvicorn", "--host", "0.0.0.0", "--port", "8000", "--reload", "wsgi_app:app"]

  auth_jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: yp_auth_jaeger
    depends_on:
      - auth_api
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - yp_network
